
title: "Polarized cortical assembloids (polCAs)"
short_title: "polCAs"
subtitle: |
   Here the code used to analyse polCAs Single Cell data
   
   ![plot](./figures/FigureGithub.png)
   
   
   base docker image can be retrieved via docker pull testalab/downstream:polaroid-0.1.3
   
   list of additional libraries installed locally can be found in data/env/python3_libs.txt and data/env/R_libs.txt
   
   Data should be placed as follows:<br>   
   Anndata of Badhuri et. al (10.1038/s41586-021-03910-8)    ./data/Badhuri_atlas.h5ad<br>   
   Ppoliudakis et. al(10.1016/j.neuron.2019.06.011):    ./data/Geschwind_atlas.h5ad<br>   
   Raw data of experiments (control1_piece1, control1_piece2 ... polaroid3_distal):    ./data<br>   
   or pre-processed polCAs (optional):    ./outdir/02C_Preprocess_final.h5ad


final: |
   Repository will be complete upon publication

pages:

  Badhuri0.Preprocess:
    notebook: "Badhuri0.Preprocess.ipynb"
    description: |

  Badhuri01B.ProgenitorsReanalysis:
    notebook: "Badhuri01B.ProgenitorsReanalysis.ipynb"
    description: |

  Badhuri01C.CyclingReanalysis:
    notebook: "Badhuri01C.CyclingReanalysis.ipynb"
    description: |

  Badhuri02.preBulk:
    notebook: "Badhuri02.preBulk.ipynb"
    description: |

  Badhuri02B.pseudoBulking:
    notebook: "Badhuri02B.pseudoBulking.ipynb"
    description: |

  Badhuri03A_Neurons.3pointsModel:
    notebook: "Badhuri03A_Neurons.3pointsModel.pBulk_byArea_scaling.ipynb"
    description: |

  Badhuri03B_Progenitors.3pointsModel:
    notebook: "Badhuri03B_Progenitors.3pointsModel.pBulk_byArea_scaling.ipynb"
    description: |

  Badhuri03C_Cycling.3pointsModel:
    notebook: "Badhuri03C_Cycling.3pointsModel.pBulk_byArea_scaling.ipynb"
    description: |

  polCAs01_RawImport:
    notebook: "polCAs01_RawImport.ipynb"
    description: |

  polCAs02_Preprocess_Gruffi:
    notebook: "polCAs02_Preprocess_Gruffi.ipynb"
    description: |

  polCAs03_Dimreduct_exploration:
    notebook: "polCAs03_Dimreduct_exploration.ipynb"
    description: |

  polCAs04_Dimreduct_inDepthMarkers:
    notebook: "polCAs04_Dimreduct_inDepthMarkers.ipynb"
    description: |

  polCAs04.2_Differential_abundance:
    notebook: "polCAs04.2_Differential_abundance.ipynb"
    description: |

  polCAs05_RG_and_Neurons_Focus:
    notebook: "polCAs05_RG_and_Neurons_Focus.ipynb"
    description: |

  polCAs06_Dimreduct_inDepthCompositions:
    notebook: "polCAs06_Dimreduct_inDepthCompositions.ipynb"
    description: |

  polCAs07B_Correlation_celltypes_areas:
    notebook: "polCAs07B_Correlation_celltypes_areas.ipynb"
    description: |

  polCAs07_Correlation_celltypes:
    notebook: "polCAs07_Correlation_celltypes.ipynb"
    description: |

  polCAs08_Developmental_Trajectories:
    notebook: "polCAs08_Developmental_Trajectories.ipynb"
    description: |

  polCAsCycling01_Selection:
    notebook: "polCAsCycling01_Selection.ipynb"
    description: |

  polCAsCycling02_pBulk:
    notebook: "polCAsCycling02_pBulk.ipynb"
    description: |

  polCAsCycling03_fg8_tomato_check:
    notebook: "polCAsCycling03_fg8_tomato_check.ipynb"
    description: |

  polCAsCycling04_pBulk_bySegment.DEA:
    notebook: "polCAsCycling04_pBulk_bySegment.DEA.ipynb"
    description: |

  polCAsCycling05A_POLAROIDS_BadhuriSpace:
    notebook: "polCAsCycling05A_POLAROIDS_BadhuriSpace.ipynb"
    description: |

  polCAsCycling05B_CONTROLS_BadhuriSpace:
    notebook: "polCAsCycling05B_CONTROLS_BadhuriSpace.ipynb"
    description: |

  polCAsCycling05C_ALL_BadhuriSpace:
    notebook: "polCAsCycling05C_ALL_BadhuriSpace.ipynb"
    description: |

  polCAsProgenitors01_Selection:
    notebook: "polCAsProgenitors01_Selection.ipynb"
    description: |

  polCAsProgenitors02_pBulk:
    notebook: "polCAsProgenitors02_pBulk.ipynb"
    description: |

  polCAsProgenitors03_fg8_tomato_check:
    notebook: "polCAsProgenitors03_fg8_tomato_check.ipynb"
    description: |

  polCAsProgenitors04_pBulk_bySegment.DEA:
    notebook: "polCAsProgenitors04_pBulk_bySegment.DEA.ipynb"
    description: |

  polCAsProgenitors05A_POLAROIDSBadhuriSpace:
    notebook: "polCAsProgenitors05A_POLAROIDSBadhuriSpace.ipynb"
    description: |

  polCAsProgenitors05B_CONTROLS_BadhuriSpace:
    notebook: "polCAsProgenitors05B_CONTROLS_BadhuriSpace.ipynb"
    description: |

  polCAsProgenitors05C_ALL_BadhuriSpace:
    notebook: "polCAsProgenitors05C_ALL_BadhuriSpace.ipynb"
    description: |

  polCAsNeurons01_Selection:
    notebook: "polCAsNeurons01_Selection.ipynb"
    description: |

  polCAsNeurons02_pBulk:
    notebook: "polCAsNeurons02_pBulk.ipynb"
    description: |

  polCAsNeurons03_fg8_tomato_check:
    notebook: "polCAsNeurons03_fg8_tomato_check.ipynb"
    description: |

  polCAsNeurons04_pBulk_bySegment.DEA:
    notebook: "polCAsNeurons04_pBulk_bySegment.DEA.ipynb"
    description: |

  polCAsNeurons05A_POLAROIDS_BadhuriSpace:
    notebook: "polCAsNeurons05A_POLAROIDS_BadhuriSpace.ipynb"
    description: |

  polCAsNeurons05B_CONTROLS_BadhuriSpace:
    notebook: "polCAsNeurons05B_CONTROLS_BadhuriSpace.ipynb"
    description: |

  polCAsNeurons05C_ALL_BadhuriSpace:
    notebook: "polCAsNeurons05C_ALL_BadhuriSpace.ipynb"
    description: |

  MfuzzTrends:
    notebook: "MfuzzTrends.ipynb"
    description: |