
title: "Polarized cortical assembloids (polCAs)"
short_title: "polCAs"
subtitle: |
   Here the code used to analyse polCAs Single Cell data
   
   Data should be placed as follows:
   
   Anndata of Badhuri et. al (10.1038/s41586-021-03910-8)    ./data/Badhuri_atlas.h5ad
   
   Ppoliudakis et. al(10.1016/j.neuron.2019.06.011):    ./data/Geschwind_atlas.h5ad   
   
   Raw data of experiments (control1_piece1, control1_piece2 ... polaroid3_distal):    ./data
   
   pre-processed polCAs (optional):    ./outdir/02C_Preprocess_final.h5ad


final: |
   Repository will be complete upon publication

pages:

  raw data import:
    notebook: "01_RawImport.ipynb"
    description: |

