
title: "Polarized cortical assembloids (polCAs)"
short_title: "polCAs"
subtitle: |
   Here the code used to analyse polCAs Single Cell data
   

final: |
   Repository will be complete upon publication

pages:

  raw data import:
    notebook: "01_RawImport.ipynb"
    description: |

